### PR TITLE
Changed the arguements values for the area

### PR DESCRIPTION
**Pull request by muga-southbridge**
Just changed the values for the arguements in the test-branch's nestarea.c

### CODE REVIEW

**Review by antonymuga — CHANGES_REQUESTED** [review]
Put in multiples of 15 instead.

**Comment by muga-southbridge** [comment]
Ok, done.

**Comment by muga-southbridge** [comment]
Okay, I'm implementing multiples of 15.

**Comment by antonymuga** [comment]
Awesome work.

**Comment by muga-southbridge** [comment]
No, we really need you to merge.

**Comment by antonymuga** [comment]
Ok, now we're truly done.

**Pull request closed without merging**
